### ISSUE TITLE
Lamassemble failing

### ISSUE THREAD

**Issue by playerpool** [JGEnglishLab/ConSeqUMI#29]
_Ran into some problems with lamassemble consensus generation with newly installed ConSeqUMI in Ubuntu. It sends the initial files to the cores  specified but then errors after a few minutes:_

---> 00:00:30:  ***** 1589 reads: generating consensus for /home/u6033588@path.utah.edu/Desktop/pAAV-hSyn-eGFP/barcode01/ConSeqUMI-umi-20230510-111441/bins/targetSequenceBin0023.fastq

Traceback (most recent call last):
  File "/home/****@path.utah.edu/Programs/anaconda3/envs/conseq/bin/conseq", line 8, in <module>
    sys.exit(main())
  File "/home/****@path.utah.edu/Desktop/conseq/ConSeqUMI/src/ConSeqUMI/conseq.py", line 23, in main
    consensus.main(args)
  File "/home/****@path.utah.edu/Desktop/conseq/ConSeqUMI/src/ConSeqUMI/consensus/consensus.py", line 71, in main
    SeqIO.write([futureProcess.result()], output_handle, outputFileType)
  File "/home/****@path.utah.edu/Programs/anaconda3/envs/conseq/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/home/****@path.utah.edu/Programs/anaconda3/envs/conseq/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

Process finished.

_The Pairwise method had no issue with the same .fastq files. We didn't try Medaka._

**Comment by CCranney** [comment]
Sounds good. I suspect that the multi-thread option, and the basis upon which the multi-thread option exists, can be problematic when running non-conseq processes through it (like lamassemble and medaka). I'm going to make the multi-thread code conditional, or optional, so it can be bypassed if they don't interact well.

In the meantime, here's a bash script I wrote that will run through lamassemble. You can use this if you need lamassemble on this dataset as a crutch until the option is implemented.

```
inputDir=<path to input directory>
matFilePath=<path to conseq>ConSeqUMI/dependencies_download/promethion.mat
outputDir=<path to output directory>
count=0
for file in $inputDir*
do
  outputFile="$outputDir""$count"".fasta"
  ((count++))
  lamassemble $matFilePath --end -g60 -m 40 -f fastq "$file" > $outputFile
done
```

**Comment by CCranney** [comment]
As an update, I've been in contact with @playerpool. It looks like this error came from missing a portion of the install instructions (the `lastal` update portion). So the significance of this issue is more pre-emptive than a fix - I foresee this causing problems, and would like an "off" switch in case it does.
